CC=lm32-rtems4.10-gcc
CFLAGS=-O2 -mmultiply-enabled -mdivide-enabled -mbarrel-shift-enabled -msign-extend-enabled -DPRINTF_FLOAT -I$(MMDIR)/software/include
AR=lm32-rtems4.10-ar
RANLIB=lm32-rtems4.10-ranlib

include ../subdir.mak
