#!/bin/sh

echo "/* This file is automatically generated by $0 */" > mtk.h
echo "#ifndef __MTK_H" >> mtk.h
echo "#define __MTK_H" >> mtk.h
for i in *.h; do
	if [ $i != "mtk.h" ]; then
		echo "#include <$i>" >> mtk.h
	fi
done
echo "#endif /* __MTK_H */" >> mtk.h
