CC=lm32-linux-gcc
CFLAGS=-O2 -mmultiply-enabled -mdivide-enabled -mbarrel-shift-enabled -msign-extend-enabled -DPRINTF_FLOAT -I$(MMDIR)/software/include
AR=lm32-linux-ar
RANLIB=lm32-linux-ranlib

include ../subdir.mak
